spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application:
    name: xxx123
---
spring:
  profiles: test    #测试环境
  application:
    name: yyy456
---
spring:
  profiles: pro     #生产环境
  application:
    name: zzz789
#保存为UTF-8
  
