spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application:
    name: xxx
---
spring:
  profiles: test    #测试环境
  application:
    name: yyy
---
spring:
  profiles: pro     #生产环境
  application:
    name: zzz
#保存为UTF-8
  